version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  # user_management:
  #   image: user_management
  #   container_name: user_management
  #   build: .
  #   environment:
  #     NODE_ENV: development
  #     DATABASE_NAME: user
  #     MONGO_CONNECTION_URI: ''
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   command: npm run dev
